apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloud-pro-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: cloud-pro.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cloud-pro-service
            port:
              number: 80
